--- #YAML:1.0
name:                WWW-SmugMug-API
version:             1.02
abstract:            Perl wrapper for the SmugMug API
license:             ~
author:              
    - Paul Arthur <flowerysong00@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    JSON:                          0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
